#! /bin/bash

function install() {
    sudo apt-get install -y $1 >/dev/null 2>&1 
}

programs="git default-jdk maven" 

echo "Installing web-server essentials... "

sudo apt-get update >/dev/null 2>&1 

echo "Starting to install extra programs"

for program in $programs
do 
    echo "Current package: $program" 
    install $program 
done 

echo "All done! Not sure what you should do now - maybe access webserver from localhost:8081 or go 'vagrant ssh' to access the server." 